channels:
- conda-forge
dependencies:
- python =3.8
- intake==0.6.6
- aiohttp==3.8.3
- dask[complete]
- pandas==1.5.0
- matplotlib==3.6.1
- pip
- pip:
  - git+https://github.com/Open-Earth-Foundation/intake-OpenClimate.git#egg=intake-OpenClimate